# Masked Convolution

## Basic usage

The way you use `masked-convolution` is fairly simple. First, import it.

In [1]:
from masked_convolution import MaskedConvolution

Then, once imported you can just use it as a decorator for Torch convolution layers.

In [2]:
import torch
from torch import nn

In [3]:
conv_1 = nn.Conv1d(1, 1, 3)
conv_2 = nn.Conv2d(1, 1, 3)
conv_3 = nn.Conv3d(1, 1, 3)

In [4]:
mconv_1 = MaskedConvolution(conv_1, [1, 0, 1])
mconv_2 = MaskedConvolution(conv_2, [
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1],
])
mconv_3 = MaskedConvolution(conv_3, [
    [
        [1, 0, 1],
        [0, 1, 0],
        [1, 0, 1],
    ],
    [
        [0, 1, 0],
        [1, 0, 1],
        [0, 1, 0],
    ],
    [
        [1, 0, 1],
        [0, 1, 0],
        [1, 0, 1],
    ],
])

Then, if we create some dummy data, you can see how it works.

In [5]:
data_1 = torch.randn((1, 1, 3))
data_2 = torch.randn((1, 1, 3, 3))
data_3 = torch.randn((1, 1, 3, 3, 3))

In [6]:
for data, conv in zip(
    (data_1, data_2, data_3),
    (conv_1, conv_2, conv_3)
):
    print(conv(data))

tensor([[[-0.1304]]], grad_fn=<SqueezeBackward1>)
tensor([[[[-0.1542]]]], grad_fn=<ThnnConv2DBackward>)
tensor([[[[[-0.4354]]]]], grad_fn=<SlowConv3DBackward>)


And then we can do the same for the masked convolutions.

In [7]:
for data, mconv in zip(
    (data_1, data_2, data_3),
    (mconv_1, mconv_2, mconv_3)
):
    print(mconv(data))

tensor([[[-0.4534]]], grad_fn=<SqueezeBackward1>)
tensor([[[[0.2355]]]], grad_fn=<ThnnConv2DBackward>)
tensor([[[[[-0.1386]]]]], grad_fn=<SlowConv3DBackward>)
